models:
  - name: face-reidentification-retail-0095

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        device: CPU
        model:   Retail/object_reidentification/face/mobilenet_based/dldt/face-reidentification-retail-0095.xml
        weights: Retail/object_reidentification/face/mobilenet_based/dldt/face-reidentification-retail-0095.bin
        adapter: reid

      - framework: dlsdk
        tags:
          - FP32
        device: GPU
        model:   Retail/object_reidentification/face/mobilenet_based/dldt/face-reidentification-retail-0095.xml
        weights: Retail/object_reidentification/face/mobilenet_based/dldt/face-reidentification-retail-0095.bin
        adapter: reid

      - framework: dlsdk
        tags:
          - FP16
        device: GPU
        model:   Retail/object_reidentification/face/mobilenet_based/dldt/face-reidentification-retail-0095-fp16.xml
        weights: Retail/object_reidentification/face/mobilenet_based/dldt/face-reidentification-retail-0095-fp16.bin
        adapter: reid

      - framework: dlsdk
        device: MYRIAD
        model:   Retail/object_reidentification/face/mobilenet_based/dldt/face-reidentification-retail-0095-fp16.xml
        weights: Retail/object_reidentification/face/mobilenet_based/dldt/face-reidentification-retail-0095-fp16.bin
        adapter: reid

      - framework: dlsdk
        device: HDDL
        model:   Retail/object_reidentification/face/mobilenet_based/dldt/face-reidentification-retail-0095-fp16.xml
        weights: Retail/object_reidentification/face/mobilenet_based/dldt/face-reidentification-retail-0095-fp16.bin
        adapter: reid

      - framework: dlsdk
        tags:
          - A10_devkit
          - FP16
        device: HETERO:FPGA,CPU
        model:   Retail/object_reidentification/face/mobilenet_based/dldt/face-reidentification-retail-0095.xml
        weights: Retail/object_reidentification/face/mobilenet_based/dldt/face-reidentification-retail-0095.bin
        adapter: reid
        bitstream: 2019R1_A10DK_FP16_SSD300.aocx

      - framework: dlsdk
        tags:
          - A10_devkit
          - FPGA11
        device: HETERO:FPGA,CPU
        model:   Retail/object_reidentification/face/mobilenet_based/dldt/face-reidentification-retail-0095.xml
        weights: Retail/object_reidentification/face/mobilenet_based/dldt/face-reidentification-retail-0095.bin
        adapter: reid
        bitstream: 2019R1_A10DK_FP11_CaffeMobileNet.aocx

      - framework: dlsdk
        tags:
          - HDDL-F
          - FP16
        device: HETERO:FPGA,CPU
        model:   Retail/object_reidentification/face/mobilenet_based/dldt/face-reidentification-retail-0095.xml
        weights: Retail/object_reidentification/face/mobilenet_based/dldt/face-reidentification-retail-0095.bin
        adapter: reid
        bitstream: 2019R1_PL1_FP16_MobileNet_Clamp.aocx

      - framework: dlsdk
        tags:
          - HDDL-F
          - FP11
        device: HETERO:FPGA,CPU
        model:   Retail/object_reidentification/face/mobilenet_based/dldt/face-reidentification-retail-0095.xml
        weights: Retail/object_reidentification/face/mobilenet_based/dldt/face-reidentification-retail-0095.bin
        adapter: reid
        bitstream: 2019R1_PL1_FP11_MobileNetCaffe.aocx

    datasets:
      - name: lfw
        data_source: LFW/lfw
        annotation_conversion:
          converter: face_reid_pairwise
          pairs_file: LFW/annotation/pairs.txt
          landmarks_file: LFW/annotation/lfw_landmark.txt

        preprocessing:
          - type: point_alignment
            size: 400
          - type: resize
            size: 128

        metrics:
          - type: pairwise_accuracy_subsets
