models:
  - name: face-detection-adas-0001

      - framework: dlsdk
        device: CPU
        model:   Transportation/object_detection/face/pruned_mobilenet_reduced_ssd_shared_weights/dldt/face-detection-adas-0001.xml
        weights: Transportation/object_detection/face/pruned_mobilenet_reduced_ssd_shared_weights/dldt/face-detection-adas-0001.bin
        adapter: ssd
        cpu_extensions: AUTO

      - framework: dlsdk
        tags:
          - GPU32
        device: GPU
        model:   Transportation/object_detection/face/pruned_mobilenet_reduced_ssd_shared_weights/dldt/face-detection-adas-0001.xml
        weights: Transportation/object_detection/face/pruned_mobilenet_reduced_ssd_shared_weights/dldt/face-detection-adas-0001.bin
        adapter: ssd

      - framework: dlsdk
        tags:
          - GPU16
        device: GPU
        model:   Transportation/object_detection/face/pruned_mobilenet_reduced_ssd_shared_weights/dldt/face-detection-adas-0001-fp16.xml
        weights: Transportation/object_detection/face/pruned_mobilenet_reduced_ssd_shared_weights/dldt/face-detection-adas-0001-fp16.bin
        adapter: ssd

      - framework: dlsdk
        device: MYRIAD
        model:   Transportation/object_detection/face/pruned_mobilenet_reduced_ssd_shared_weights/dldt/face-detection-adas-0001-fp16.xml
        weights: Transportation/object_detection/face/pruned_mobilenet_reduced_ssd_shared_weights/dldt/face-detection-adas-0001-fp16.bin
        adapter: ssd

      - framework: dlsdk
        device: HDDL
        model:   Transportation/object_detection/face/pruned_mobilenet_reduced_ssd_shared_weights/dldt/face-detection-adas-0001-fp16.xml
        weights: Transportation/object_detection/face/pruned_mobilenet_reduced_ssd_shared_weights/dldt/face-detection-adas-0001-fp16.bin
        adapter: ssd

      - framework: dlsdk
        tags:
          - A10_devkit
          - FP16
        device: HETERO:FPGA,CPU
        model:   Transportation/object_detection/face/pruned_mobilenet_reduced_ssd_shared_weights/dldt/face-detection-adas-0001.xml
        weights: Transportation/object_detection/face/pruned_mobilenet_reduced_ssd_shared_weights/dldt/face-detection-adas-0001.bin
        adapter: ssd
        cpu_extensions: AUTO
        bitstream: 2019R1_A10DK_FP16_MobileNet_Clamp.aocx

      - framework: dlsdk
        tags:
          - A10_devkit
          - FP11
        device: HETERO:FPGA,CPU
        model:   Transportation/object_detection/face/pruned_mobilenet_reduced_ssd_shared_weights/dldt/face-detection-adas-0001.xml
        weights: Transportation/object_detection/face/pruned_mobilenet_reduced_ssd_shared_weights/dldt/face-detection-adas-0001.bin
        adapter: ssd
        cpu_extensions: AUTO
        bitstream: 2019R1_A10DK_FP11_ELU.aocx

      - framework: dlsdk
        tags:
          - HDDL-F
          - FP16
        device: HETERO:FPGA,CPU
        model:   Transportation/object_detection/face/pruned_mobilenet_reduced_ssd_shared_weights/dldt/face-detection-adas-0001.xml
        weights: Transportation/object_detection/face/pruned_mobilenet_reduced_ssd_shared_weights/dldt/face-detection-adas-0001.bin
        adapter: ssd
        cpu_extensions: AUTO
        bitstream: 2019R1_PL1_FP16_ResNet_SqueezeNet_VGG_ELU.aocx

      - framework: dlsdk
        tags:
          - HDDL-F
          - FP11
        device: HETERO:FPGA,CPU
        model:   Transportation/object_detection/face/pruned_mobilenet_reduced_ssd_shared_weights/dldt/face-detection-adas-0001.xml
        weights: Transportation/object_detection/face/pruned_mobilenet_reduced_ssd_shared_weights/dldt/face-detection-adas-0001.bin
        adapter: ssd
        cpu_extensions: AUTO
        bitstream: 2019R1_PL1_FP11_MobileNetCaffe.aocx

    datasets:
      - name: wider
        data_source: WIDER_val/images
        annotation_conversion:
          converter: wider
          annotation_file: wider_face_split/wider_face_val_bbx_gt.txt

        preprocessing:
          - type: resize
            dst_width: 672
            dst_height: 384

        postprocessing:
          - type: resize_prediction_boxes
          - type: filter
            height_range: 100
            apply_to: annotation

        metrics:
          - type: map
            ignore_difficult: True
            include_boundaries: False
            allow_multiple_matches_per_ignored: True
            use_filtered_tp: True
