models:
  - name: landmarks-regression-retail-0009

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        device: CPU
        model:   Retail/object_attributes/landmarks_regression/0009/dldt/landmarks-regression-retail-0009.xml
        weights: Retail/object_attributes/landmarks_regression/0009/dldt/landmarks-regression-retail-0009.bin
        adapter: landmarks_regression
        cpu_extensions: AUTO

      - framework: dlsdk
        tags:
          - FP32
        device: GPU
        model:   Retail/object_attributes/landmarks_regression/0009/dldt/landmarks-regression-retail-0009.xml
        weights: Retail/object_attributes/landmarks_regression/0009/dldt/landmarks-regression-retail-0009.bin
        adapter: landmarks_regression

      - framework: dlsdk
        tags:
          - FP16
        device: GPU
        model:   Retail/object_attributes/landmarks_regression/0009/dldt/landmarks-regression-retail-0009-fp16.xml
        weights: Retail/object_attributes/landmarks_regression/0009/dldt/landmarks-regression-retail-0009-fp16.bin
        adapter: landmarks_regression

      - framework: dlsdk
        device: MYRIAD
        model:   Retail/object_attributes/landmarks_regression/0009/dldt/landmarks-regression-retail-0009-fp16.xml
        weights: Retail/object_attributes/landmarks_regression/0009/dldt/landmarks-regression-retail-0009-fp16.bin
        adapter: landmarks_regression

      - framework: dlsdk
        device: HDDL
        model:   Retail/object_attributes/landmarks_regression/0009/dldt/landmarks-regression-retail-0009-fp16.xml
        weights: Retail/object_attributes/landmarks_regression/0009/dldt/landmarks-regression-retail-0009-fp16.bin
        adapter: landmarks_regression

      - framework: dlsdk
        tags:
          - A10_devkit
          - FP16
        device: HETERO:FPGA,CPU
        model:   Retail/object_attributes/landmarks_regression/0009/dldt/landmarks-regression-retail-0009.xml
        weights: Retail/object_attributes/landmarks_regression/0009/dldt/landmarks-regression-retail-0009.bin
        adapter: landmarks_regression
        cpu_extensions: AUTO
        bitstream: 2019R1_A10DK_FP16_AlexNet_GoogleNet.aocx

      - framework: dlsdk
        tags:
          - A10_devkit
          - FP11
        device: HETERO:FPGA,CPU
        model:   Retail/object_attributes/landmarks_regression/0009/dldt/landmarks-regression-retail-0009.xml
        weights: Retail/object_attributes/landmarks_regression/0009/dldt/landmarks-regression-retail-0009.bin
        adapter: landmarks_regression
        cpu_extensions: AUTO
        bitstream: 2019R1_A10DK_FP11_RMNet.aocx

      - framework: dlsdk
        tags:
          - HDDL-F
          - FP16
        device: HETERO:FPGA,CPU
        model:   Retail/object_attributes/landmarks_regression/0009/dldt/landmarks-regression-retail-0009.xml
        weights: Retail/object_attributes/landmarks_regression/0009/dldt/landmarks-regression-retail-0009.bin
        adapter: landmarks_regression
        cpu_extensions: AUTO
        bitstream: 2019R1_PL1_FP16_ResNet_SqueezeNet_VGG_ELU.aocx

      - framework: dlsdk
        tags:
          - HDDL-F
          - FP11
        device: HETERO:FPGA,CPU
        model:   Retail/object_attributes/landmarks_regression/0009/dldt/landmarks-regression-retail-0009.xml
        weights: Retail/object_attributes/landmarks_regression/0009/dldt/landmarks-regression-retail-0009.bin
        adapter: landmarks_regression
        cpu_extensions: AUTO
        bitstream: 2019R1_PL1_FP11_RMNet.aocx

    datasets:
      - name: vgg2face
        data_source: VGGFaces2/test
        annotation_conversion:
          converter: landmarks_regression
          landmarks_csv_file: VGGFaces2/bb_landmark/loose_landmark_test.csv
          bbox_csv_file: VGGFaces2/bb_landmark/loose_bb_test.csv

        preprocessing:
          - type: crop_rect
          - type: resize
            size: 48

        postprocessing:
          - type: normalize_landmarks_points
            use_annotation_rect: True

        metrics:
          - type: per_point_normed_error
            presenter: print_vector
          - type: normed_error
