models:
  - name: person-reidentification-retail-0031

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        device: CPU
        model:   Security/object_attributes/pedestrian/person-attributes-recognition-crossroad-0031/dldt/person-attributes-recognition-crossroad-0031.xml
        weights: Security/object_attributes/pedestrian/person-attributes-recognition-crossroad-0031/dldt/person-attributes-recognition-crossroad-0031.bin
        adapter: reid

      - framework: dlsdk
        tags:
          - INT8
        device: CPU
        model:   Security/object_attributes/pedestrian/person-attributes-recognition-crossroad-0031/dldt/person-attributes-recognition-crossroad-0031-int8.xml
        weights: Security/object_attributes/pedestrian/person-attributes-recognition-crossroad-0031/dldt/person-attributes-recognition-crossroad-0031-int8.bin
        adapter: reid

      - framework: dlsdk
        tags:
          - FP32
        device: GPU
        model:   Security/object_attributes/pedestrian/person-attributes-recognition-crossroad-0031/dldt/person-attributes-recognition-crossroad-0031.xml
        weights: Security/object_attributes/pedestrian/person-attributes-recognition-crossroad-0031/dldt/person-attributes-recognition-crossroad-0031.bin
        adapter: reid

      - framework: dlsdk
        tags:
          - FP16
        device: GPU
        model:   Security/object_attributes/pedestrian/person-attributes-recognition-crossroad-0031/dldt/person-attributes-recognition-crossroad-0031-fp16.xml
        weights: Security/object_attributes/pedestrian/person-attributes-recognition-crossroad-0031/dldt/person-attributes-recognition-crossroad-0031-fp16.bin
        adapter: reid

      - framework: dlsdk
        device: MYRIAD
        model:   Security/object_attributes/pedestrian/person-attributes-recognition-crossroad-0031/dldt/person-attributes-recognition-crossroad-0031-fp16.xml
        weights: Security/object_attributes/pedestrian/person-attributes-recognition-crossroad-0031/dldt/person-attributes-recognition-crossroad-0031-fp16.bin
        adapter: reid

      - framework: dlsdk
        device: HDDL
        model:   Security/object_attributes/pedestrian/person-attributes-recognition-crossroad-0031/dldt/person-attributes-recognition-crossroad-0031-fp16.xml
        weights: Security/object_attributes/pedestrian/person-attributes-recognition-crossroad-0031/dldt/person-attributes-recognition-crossroad-0031-fp16.bin
        adapter: reid

      - framework: dlsdk
        tags:
          - A10_devkit
          - FP16
        device: HETERO:FPGA,CPU
        model:   Security/object_attributes/pedestrian/person-attributes-recognition-crossroad-0031/dldt/person-attributes-recognition-crossroad-0031.xml
        weights: Security/object_attributes/pedestrian/person-attributes-recognition-crossroad-0031/dldt/person-attributes-recognition-crossroad-0031.bin
        adapter: reid
        bitstream: 2019R1_A10DK_FP16_ELU.aocx

      - framework: dlsdk
        tags:
          - A10_devkit
          - FP11
        device: HETERO:FPGA,CPU
        model:   Security/object_attributes/pedestrian/person-attributes-recognition-crossroad-0031/dldt/person-attributes-recognition-crossroad-0031.xml
        weights: Security/object_attributes/pedestrian/person-attributes-recognition-crossroad-0031/dldt/person-attributes-recognition-crossroad-0031.bin
        adapter: reid
        bitstream: 2019R1_A10DK_FP11_ELU.aocx

      - framework: dlsdk
        tags:
          - HDDL-F
          - FP16
        device: HETERO:FPGA,CPU
        model:   Security/object_attributes/pedestrian/person-attributes-recognition-crossroad-0031/dldt/person-attributes-recognition-crossroad-0031.xml
        weights: Security/object_attributes/pedestrian/person-attributes-recognition-crossroad-0031/dldt/person-attributes-recognition-crossroad-0031.bin
        adapter: reid
        bitstream: 2019R1_PL1_FP16_ResNet_SqueezeNet_VGG_ELU.aocx

      - framework: dlsdk
        tags:
          - HDDL-F
          - FP11
        device: HETERO:FPGA,CPU
        model:   person-reidentification-retail-0031/FP32/person-reidentification-retail-0031.xml
        weights: person-reidentification-retail-0031/FP32/person-reidentification-retail-0031.bin
        adapter: reid
        bitstream: 2019R1_PL1_FP11_ELU.aocx

    datasets:
      - name: market1501
        reader: pillow_imread
        data_source: Market-1501-v15.09.15
        annoation_conversion:
          converter: market1501
          data_dir: Market-1501-v15.09.15

        preprocessing:
          - type: bgr_to_rgb
          - type: resize
            dst_width: 48
            dst_height: 96
            use_pillow: True
            interpolation: ANTIALIAS

        metrics:
          - name: rank@1
            type: cmc
            top_k: 1

          - type: reid_map
