models:
  - name: person-reidentification-retail-0079

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        device: CPU
        model:   Retail/object_reidentification/pedestrian/rmnet_based/0079/dldt/person-reidentification-retail-0079.xml
        weights: Retail/object_reidentification/pedestrian/rmnet_based/0079/dldt/person-reidentification-retail-0079.bin
        adapter: reid

      - framework: dlsdk
        tags:
          - INT8
        device: CPU
        model:   Retail/object_reidentification/pedestrian/rmnet_based/0079/dldt/person-reidentification-retail-0079-int8.xml
        weights: Retail/object_reidentification/pedestrian/rmnet_based/0079/dldt/person-reidentification-retail-0079-int8.bin
        adapter: reid

      - framework: dlsdk
        tags:
          - FP32
        device: GPU
        model:   Retail/object_reidentification/pedestrian/rmnet_based/0079/dldt/person-reidentification-retail-0079.xml
        weights: Retail/object_reidentification/pedestrian/rmnet_based/0079/dldt/person-reidentification-retail-0079.bin
        adapter: reid

      - framework: dlsdk
        tags:
          - FP16
        device: GPU
        model:   Retail/object_reidentification/pedestrian/rmnet_based/0079/dldt/person-reidentification-retail-0079-fp16.xml
        weights: Retail/object_reidentification/pedestrian/rmnet_based/0079/dldt/person-reidentification-retail-0079-fp16.bin
        adapter: reid

      - framework: dlsdk
        device: MYRIAD
        model:   Retail/object_reidentification/pedestrian/rmnet_based/0079/dldt/person-reidentification-retail-0079-fp16.xml
        weights: Retail/object_reidentification/pedestrian/rmnet_based/0079/dldt/person-reidentification-retail-0079-fp16.bin
        adapter: reid

      - framework: dlsdk
        device: HDDL
        model:   Retail/object_reidentification/pedestrian/rmnet_based/0079/dldt/person-reidentification-retail-0079-fp16.xml
        weights: Retail/object_reidentification/pedestrian/rmnet_based/0079/dldt/person-reidentification-retail-0079-fp16.bin
        adapter: reid

      - framework: dlsdk
        tags:
          - A10_devkit
          - FP16
        device: HETERO:FPGA,CPU
        model:   Retail/object_reidentification/pedestrian/rmnet_based/0079/dldt/person-reidentification-retail-0079.xml
        weights: Retail/object_reidentification/pedestrian/rmnet_based/0079/dldt/person-reidentification-retail-0079.bin
        adapter: reid
        bitstream: 2019R1_A10DK_FP16_RMNet.aocx

      - framework: dlsdk
        tags:
          - A10_devkit
          - FP11
        device: HETERO:FPGA,CPU
        model:   Retail/object_reidentification/pedestrian/rmnet_based/0079/dldt/person-reidentification-retail-0079.xml
        weights: Retail/object_reidentification/pedestrian/rmnet_based/0079/dldt/person-reidentification-retail-0079.bin
        adapter: reid
        bitstream: 2019R1_A10DK_FP11_ELU.aocx

      - framework: dlsdk
        tags:
          - HDDL-F
          - FP16
        device: HETERO:FPGA,CPU
        model:   Retail/object_reidentification/pedestrian/rmnet_based/0079/dldt/person-reidentification-retail-0079.xml
        weights: Retail/object_reidentification/pedestrian/rmnet_based/0079/dldt/person-reidentification-retail-0079.bin
        adapter: reid
        bitstream: 2019R1_PL1_FP16_RMNet.aocx

      - framework: dlsdk
        tags:
          - HDDL-F
          - FP11
        device: HETERO:FPGA,CPU
        model:   Retail/object_reidentification/pedestrian/rmnet_based/0079/dldt/person-reidentification-retail-0079.xml
        weights: Retail/object_reidentification/pedestrian/rmnet_based/0079/dldt/person-reidentification-retail-0079.bin
        adapter: reid
        bitstream: 2019R1_PL1_FP11_ELU.aocx

    datasets:
      - name: market1501
        data_source: Market-1501-v15.09.15
        annoation_conversion:
          converter: market1501
          data_dir: Market-1501-v15.09.15

        preprocessing:
          - type: resize
            dst_width: 64
            dst_height: 160

        metrics:
          - name: rank@1
            type: cmc
            top_k: 1

          - type: reid_map
