models:
  - name: resnet50-binary-0001

    launchers:
      - framework: dlsdk
        tags:
          - INT1
        device: CPU
        model:   PublicCompressed/classification/resnet50_binary/dldt/resnet50-binary-0001.xml
        weights: PublicCompressed/classification/resnet50_binary/dldt/resnet50-binary-0001.bin
        adapter: classification


    datasets:
      - name: imagenet
        data_source: ImageNet
        annotation_conversion:
          converter: imagenet
          annotation_file: val.txt
        annotation: imagenet.pickle
        reader: pillow_imread

        preprocessing:
        - type: resize
          size: 256
          aspect_ratio_scale: greater
          use_pillow: True
          interpolation: BILINEAR
        - type: crop
          size: 224
          use_pillow: True
        - type: bgr_to_rgb

        metrics:
          - name: accuracy@top1
            type: accuracy
            top_k: 1
          - name: accuracy@top5
            type: accuracy
            top_k: 5
