models:
  - name: text-recognition-0012

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        device: CPU
        model:   Retail/text_recognition/bilstm_crnn_bilstm_decoder/0012/dldt/text-recognition-0012.xml
        weights: Retail/text_recognition/bilstm_crnn_bilstm_decoder/0012/dldt/text-recognition-0012.bin
        adapter: beam_search_decoder
        cpu_extensions: AUTO

      - framework: dlsdk
        tags:
          - FP32
        device: GPU
        model:   Retail/text_recognition/bilstm_crnn_bilstm_decoder/0012/dldt/text-recognition-0012.xml
        weights: Retail/text_recognition/bilstm_crnn_bilstm_decoder/0012/dldt/text-recognition-0012.bin
        adapter: beam_search_decoder

      - framework: dlsdk
        tags:
          - FP16
        device: GPU
        model:   Retail/text_recognition/bilstm_crnn_bilstm_decoder/0012/dldt/text-recognition-0012-fp16.xml
        weights: Retail/text_recognition/bilstm_crnn_bilstm_decoder/0012/dldt/text-recognition-0012-fp16.bin
        adapter: beam_search_decoder

      - framework: dlsdk
        device: MYRIAD
        model:   Retail/text_recognition/bilstm_crnn_bilstm_decoder/0012/dldt/text-recognition-0012-fp16.xml
        weights: Retail/text_recognition/bilstm_crnn_bilstm_decoder/0012/dldt/text-recognition-0012-fp16.bin
        adapter: beam_search_decoder

      - framework: dlsdk
        device: HDDL
        model:   Retail/text_recognition/bilstm_crnn_bilstm_decoder/0012/dldt/text-recognition-0012-fp16.xml
        weights: Retail/text_recognition/bilstm_crnn_bilstm_decoder/0012/dldt/text-recognition-0012-fp16.bin
        adapter: beam_search_decoder

      - framework: dlsdk
        tags:
          - A10_devkit
          - FP16
        device: HETERO:FPGA,CPU
        model:   Retail/text_recognition/bilstm_crnn_bilstm_decoder/0012/dldt/text-recognition-0012.xml
        weights: Retail/text_recognition/bilstm_crnn_bilstm_decoder/0012/dldt/text-recognition-0012.bin
        adapter: beam_search_decoder
        cpu_extensions: AUTO
        bitstream: 2019R1_A10DK_FP16_AlexNet_GoogleNet.aocx

      - framework: dlsdk
        tags:
          - A10_devkit
          - FP11
        device: HETERO:FPGA,CPU
        model:   Retail/text_recognition/bilstm_crnn_bilstm_decoder/0012/dldt/text-recognition-0012.xml
        weights: Retail/text_recognition/bilstm_crnn_bilstm_decoder/0012/dldt/text-recognition-0012.bin
        adapter: beam_search_decoder
        cpu_extensions: AUTO
        bitstream: 2019R1_A10DK_FP11_AlexNet_GoogleNet_SqueezeNet.aocx

      - framework: dlsdk
        tags:
          - HDDL-F
          - FP16
        device: HETERO:FPGA,CPU
        model:   Retail/text_recognition/bilstm_crnn_bilstm_decoder/0012/dldt/text-recognition-0012.xml
        weights: Retail/text_recognition/bilstm_crnn_bilstm_decoder/0012/dldt/text-recognition-0012.bin
        adapter: beam_search_decoder
        cpu_extensions: AUTO
        bitstream: 2019R1_PL1_FP16_ResNet_SqueezeNet_VGG_ELU.aocx

      - framework: dlsdk
        tags:
          - HDDL-F
          - FP11
        device: HETERO:FPGA,CPU
        model:   Retail/text_recognition/bilstm_crnn_bilstm_decoder/0012/dldt/text-recognition-0012.xml
        weights: Retail/text_recognition/bilstm_crnn_bilstm_decoder/0012/dldt/text-recognition-0012.bin
        adapter: beam_search_decoder
        cpu_extensions: AUTO
        bitstream: 2019R1_PL1_FP11_AlexNet_GoogleNet.aocx

    datasets:
      - name: ICDAR2013
        data_source: ICDAR13_REC_validation/Challenge2_Test_Task3_Images
        annotation_conversion:
          converter: icdar13_recognition
          annotation_file: ICDAR13_REC_validation/gt/gt.txt.fixed.alfanumeric

        preprocessing:
          - type: bgr_to_gray
          - type: resize
            dst_width: 120
            dst_height: 32

        metrics:
          - type: character_recognition_accuracy
